# Generated by Django 3.2 on 2022-03-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20220327_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='cold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('oder_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_id', models.CharField(blank=True, max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
