# Generated by Django 4.0.4 on 2022-05-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_name_delete_cold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Speeds', models.CharField(choices=[('slow', 'slow'), ('modrate', 'modrate')], max_length=200, null=True)),
                ('num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.name')),
            ],
        ),
    ]
