# Generated by Django 4.0.4 on 2022-06-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_fast'),
    ]

    operations = [
        migrations.CreateModel(
            name='oom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
